In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

# Numpy Array and Shaping

In [2]:
# python'da liste olarak adlandırılan ifade numpy'de dizi (array) olarak ifade edilmektedir.

dizi=np.array([1,2,3,4,5,6,7,8])

print(type(dizi))

# Yukarıda tek boyulu bir dizi tanımlanmıştır.
# numpy array'leri içerisinde sadece tek tip veri tipi olmalıdır. Heterojen veri tipleri olamaz.

<class 'numpy.ndarray'>


In [14]:
dizi2=np.array([[1,2],[3,4],[8,6],[7,8]])

# Yukarıda çok boyutlu bir dizi tanımlanmıştır. Çok boyutlu diziler aynı zamanda matris yapısına sahiptir.

print(dizi)
print(dizi2)

print(dizi2.shape)      # matris yapsını döndürdü. 4x2'lik bir matris olduğunu söyledi bize.

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [8 6]
 [7 8]]
(4, 2)


In [15]:
# Tek boyutlu bir dizi içerisinden matris çıkarabilmek için .reshape() metodu kullanılır.

dizi3=dizi.reshape(4,2)
dizi4=dizi.reshape(2,4)

print(dizi3)
print(dizi4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]


# Ardışık Sayılardan Oluşan Array Oluşturmak ve Bir Aralığı Belirli Sayıda Noktaya Bölmek

In [16]:
# .arange() fonksiyonunun kullanımı;

aralık=np.arange(0,100,5)              # 0'dan 100'e kadar (100 dahil değil) olan sayıları 5'er arttırarak yazdırdı.
print(aralık)

# linspace() fonksiyonunun kullanımı;

aralık2=np.linspace(0,100,5)           # Artış sayısını değil eleman sayısını gösteren bir fonksiyondur. Bu fonksiyonda son parametre dahildir.
                                       # Son sayının dahil olmasını istemiyorsak, np.linspace(0,100,5,endpoint=false) yazmamız gerekir.
print(aralık2)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[  0.  25.  50.  75. 100.]


In [17]:
np.linspace(1,30)

array([ 1.        ,  1.59183673,  2.18367347,  2.7755102 ,  3.36734694,
        3.95918367,  4.55102041,  5.14285714,  5.73469388,  6.32653061,
        6.91836735,  7.51020408,  8.10204082,  8.69387755,  9.28571429,
        9.87755102, 10.46938776, 11.06122449, 11.65306122, 12.24489796,
       12.83673469, 13.42857143, 14.02040816, 14.6122449 , 15.20408163,
       15.79591837, 16.3877551 , 16.97959184, 17.57142857, 18.16326531,
       18.75510204, 19.34693878, 19.93877551, 20.53061224, 21.12244898,
       21.71428571, 22.30612245, 22.89795918, 23.48979592, 24.08163265,
       24.67346939, 25.26530612, 25.85714286, 26.44897959, 27.04081633,
       27.63265306, 28.2244898 , 28.81632653, 29.40816327, 30.        ])

In [18]:
# np.arrange kullanımına örnek;

# [0,12)

np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Normal Distribution(dağılım)'dan Örneklem Almak

In [19]:
# Numpy ile normal dağılım değerleri ile array oluşturma;

#(mean,std, (matrix shape)) formatında yazılır.

np.random.normal(0,1,(4,5))

array([[-0.63885157, -1.72613189, -0.72708181, -0.31907948, -0.01756393],
       [-0.15441836,  1.3364606 ,  1.2481591 ,  0.3854925 ,  0.02407005],
       [ 0.27805375,  0.38135103, -0.67353169,  0.06798819,  1.27056743],
       [ 0.201508  , -2.17723912,  0.29412396, -1.70364152, -1.63247626]])

# Random Integer'lardan Oluşan Array Oluşturmak

In [20]:
# Numpy ile random integer ile array oluşturulması

# (min,max,(matrix shape)) formatında yazılır. [min, max) Max değer görüldüğü üzere dahil değildir. 
# Tamamen random olduğu için uniform dağılımı gösterir.

np.random.randint(1,10,(3,4))

array([[6, 5, 4, 2],
       [6, 3, 9, 4],
       [3, 8, 1, 5]])

In [21]:
d={}

for _ in range(1000000):
    val=np.random.randint(1,11)

    if val not in d:
        d[val]=1
    else:
        d[val]+=1

d       # hepsi yaklaşık olarak 100_000'e yakınsadı.

{1: 99838,
 3: 99959,
 8: 100512,
 5: 100322,
 6: 99559,
 10: 100338,
 7: 100059,
 2: 100060,
 4: 99882,
 9: 99471}

# Birim matrix oluşturmak

In [22]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Array İşlemleri

In [23]:
# python'ın kendisinde listeler için çarpma operatörü tanımlı değildir.

a=[1,2,3]
b=[3,4,5]

a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [24]:
[1,2,3]*3

# Yukarda görüldüğü üzere bir listeyi pythonda çarparsak ard arda çarptığımız değer kadar birleştirir.

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [25]:
[3,4,5]+[3,4,5]+[3,4,5]

# Yukarda görüldüğü üzere bir listeyi pythonda toplarsak ard arda birleştirme işlemi yapar.

[3, 4, 5, 3, 4, 5, 3, 4, 5]

In [26]:
x=np.array([1,2,3])
y=np.array([3,4,5])

x*y

array([ 3,  8, 15])

In [27]:
x2=np.array([1,2,3])
y2=np.array([3,4,5,6])

x2*y2

# eleman sayıları aynı olmazsa error alınır.

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [28]:
n, m, p = map(int, input().split())

nexp=[]
mexp=[]

for _ in range(n):
    nexp.append(np.array(list(map(int, input().split()))))

for _ in range(m):
    mexp.append(np.array(list(map(int, input().split()))))

print(np.concatenate((nexp, mexp), axis=0))

ValueError: not enough values to unpack (expected 3, got 0)

In [29]:
a=np.arange(20).reshape(5,4) 

a.shape


(5, 4)

In [30]:
np.vsplit(a,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [31]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
a=np.arange(1,13).reshape(3,4) 
b=a[1,(1,3)]

In [33]:
b.ndim

1

numpy' de "or" veya "and" çalışmaz. or için "|", and için "&" kullanılır. not için ise "~" (tilde) işareti kullanılır. [Alt Gr + ü ile çağırılır.]

In [34]:
a=np.arange(1,21).reshape(4,5) 


In [35]:
np.any(a>4,axis=0) 

array([ True,  True,  True,  True,  True])